export const weatherCardData = [
  {
    day: "Sun",
    date: "06 / 29",
    icon: '"<BiCloudRain />",',
    title: "Rainy",
    high: "25",
    low: "17",
    windspeed: '17',
  },
  {
    day: "Mon",
    date: "30 / 06",
    icon: "<BiCloudDrizzle />",
    title: "Drizzle",
    high: "26",
    low: "19",
    windspeed: '15',
  },
  {
    day: "Tue",
    date: "01 / 07",
    icon: "<BiCloud />",
    title: "Cloudy",
    high: "24",
    low: "16",
    windspeed: '16',
  },
  {
    day: "Wed",
    date: "02 / 07",
    icon: "<BiSun />",
    title: "Sunny",
    high: "29",
    low: "23",
    windspeed: '19',
  },
  {
    day: "Thu",
    date: "03 / 07",
    icon: "<BiCloudSnow />",
    title: "Snowy",
    high: "20",
    low: "11",
    windspeed: '15',
  },
  {
    day: "Fri",
    date: "04 / 07",
    icon: "<BiWind />",
    title: "Windy",
    high: "25",
    low: "18",
    windspeed: '22',
  },
  {
    day: "Sat",
    date: "05 / 07",
    icon: "<BiCloudLightening />",
    title: "Thunderstorm",
    high: "24",
    low: "17",
    windspeed: '23',
  },
] as const;
